# Research on apartment sales ads

### Step 1. Open the data file and study the general information. 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

real_estate_data = pd.read_csv('/datasets/real_estate_data.csv',sep='\t')
print(real_estate_data.head())
print(real_estate_data.info())

   total_images  last_price  total_area first_day_exposition  rooms  \
0            20  13000000.0       108.0  2019-03-07T00:00:00      3   
1             7   3350000.0        40.4  2018-12-04T00:00:00      1   
2            10   5196000.0        56.0  2015-08-20T00:00:00      2   
3             0  64900000.0       159.0  2015-07-24T00:00:00      3   
4             2  10000000.0       100.0  2018-06-19T00:00:00      2   

   ceiling_height  floors_total  living_area  floor is_apartment  ...  \
0            2.70          16.0         51.0      8          NaN  ...   
1             NaN          11.0         18.6      1          NaN  ...   
2             NaN           5.0         34.3      4          NaN  ...   
3             NaN          14.0          NaN      9          NaN  ...   
4            3.03          14.0         32.0     13          NaN  ...   

   kitchen_area  balcony    locality_name  airports_nearest  \
0          25.0      NaN  Санкт-Петербург           18863.0   
1       

### Conclusion

The data needs to be process in order to work with. Capslocks, duplicates, information that is not helpful, time not in format, null, and more.

### Step 2. Data preprocessing

Every column is going to be check, if it has null we will treat, impossible data too, and long unique data we will try to categorize.

In [3]:
print(real_estate_data['balcony'].unique())
real_estate_data['balcony'] = real_estate_data['balcony'].fillna(0.0)
print(real_estate_data['balcony'].unique())
print(real_estate_data['balcony'].value_counts())

[18863. 12817. 21741. ... 11751. 20151. 24665.]
84869.0
0.0
37434.0    61
21928.0    32
39946.0    30
44870.0    30
37407.0    27
           ..
25122.0     1
26768.0     1
22248.0     1
20475.0     1
14579.0     1
Name: airports_nearest, Length: 8275, dtype: int64
middle_range    14201
far_range        6760
close_range      2738
Name: airport_group, dtype: int64
[nan  2.  0.  1.  5.  4.  3.]
[0. 2. 1. 5. 4. 3.]
0.0    15277
1.0     4195
2.0     3659
5.0      304
4.0      183
3.0       81
Name: balcony, dtype: int64
[  2.7     nan   3.03   2.5    2.67   2.56   3.05   2.75   2.6    2.9
   2.8    2.55   3.     2.65   3.2    2.61   3.25   3.45   2.77   2.85
   2.64   2.57   4.15   3.5    3.3    2.71   4.     2.47   2.73   2.84
   3.1    2.34   3.4    3.06   2.72   2.54   2.51   2.78   2.76  25.
   2.58   3.7    2.52   5.2    2.87   2.66   2.59   2.     2.45   3.6
   2.92   3.11   3.13   3.8    3.15   3.55   3.16   3.62   3.12   2.53
   2.74   2.96   2.46   5.3    5.     2.79   2.95   4.06 

medium    16106
huge       3987
small       399
Name: kitchen_group, dtype: int64
[ 3350000.  5196000. 64900000. ...  3063600.  6151120. 11475000.]
763000000.0
12190.0
[18.6  34.3    nan ... 82.55 13.59 42.55]
409.7
2.0
medium    11947
small      4543
huge       4002
Name: linving_group, dtype: int64
['посёлок Шушары' 'Санкт-Петербург' 'городской посёлок Янино-1'
 'посёлок Парголово' 'посёлок Мурино' 'Ломоносов' 'Сертолово' 'Петергоф'
 'Пушкин' 'деревня Кудрово' 'Коммунар' 'Колпино'
 'поселок городского типа Красный Бор' 'Гатчина' 'поселок Мурино'
 'деревня Фёдоровское' 'Выборг' 'Кронштадт' 'Кировск'
 'деревня Новое Девяткино' 'посёлок Металлострой'
 'посёлок городского типа Сиверский' 'поселок Молодцово'
 'поселок городского типа Кузьмоловский' 'Павловск' 'деревня Пикколово'
 'Всеволожск' 'Кингисепп' 'Сестрорецк' 'деревня Куттузи'
 'поселок городского типа Ефимовский' 'посёлок Плодовое'
 'деревня Заклинье' 'поселок Торковичи' 'Красное Село' 'посёлок Понтонный'
 'Сясьстрой' 'посёлок Но

far_range      13566
close_range     6926
Name: parks_nearest_group, dtype: int64
[ 0.  2.  3.  1. nan]
[  nan  574.  234. ...   30.  171. 1134.]
[ 520.38744451  574.          234.         ...   30.          171.
 1134.        ]
1344.0
13.0
medium_range    17875
far_range        1453
close_range      1164
Name: ponds_nearest_group, dtype: int64
[ 1  2  3  4  5  0  6  7  8 14 15  9 11 19 10 16 12]
[ 2  3  4  5  6  7  8 14 15  9 11 19 10 16 12]
small     11718
medium     1192
villa       137
Name: rooms_group, dtype: int64
[False]
[ 56.   159.   100.   ...  76.26  66.86  76.75]
900.0
20.0
medium    8734
small     2933
huge      1380
Name: total_area_group, dtype: int64
[10  0  2 18  9 20 11 16 12  8  3  6  7 13 15 17 19 14 32  1  4  5 35 39
 23 21 27 24 25 28 31 22 29 26 50 42 30 37]
medium        5927
impressive    5604
few           1516
Name: total_images_group, dtype: int64


In [ ]:
print(real_estate_data['ceiling_height'].unique())
print(real_estate_data['ceiling_height'].max())
print(real_estate_data['ceiling_height'].min())
print(real_estate_data['ceiling_height'].value_counts())

real_estate_data.drop(real_estate_data[real_estate_data['ceiling_height'] > 6.0].index , inplace=True)
real_estate_data.drop(real_estate_data[real_estate_data['ceiling_height'] < 2.0].index , inplace=True)

print(real_estate_data['ceiling_height'].value_counts())
print(real_estate_data['ceiling_height'].unique())

ceil_mean = real_estate_data['ceiling_height'].mean()
real_estate_data['ceiling_height'] = real_estate_data['ceiling_height'].fillna(ceil_mean)

print(real_estate_data['ceiling_height'].unique())

In [ ]:
print(real_estate_data['days_exposition'].unique())
real_estate_data.dropna(subset=['days_exposition'], inplace=True)
print(real_estate_data['days_exposition'].unique())
print(real_estate_data['days_exposition'].max())
print(real_estate_data['days_exposition'].min())

def days_exposition_to_group(row):
    income = row['days_exposition']/365
    if income <= 1. :
        return 'new'
    elif income <= 2.:
        return 'normal'
    return 'old'

real_estate_data['days_exposition_group'] = real_estate_data.apply(days_exposition_to_group, axis=1)
print(real_estate_data['days_exposition_group'].value_counts())

In [ ]:
print(real_estate_data['first_day_exposition'].unique())
real_estate_data['first_day_exposition']= pd.to_datetime(real_estate_data['first_day_exposition'], format='%Y-%m-%dT%H:%M:%S')

In [ ]:
print(real_estate_data['floor'].unique())
print(real_estate_data['floor'].value_counts())

In [ ]:
print(real_estate_data['cityCenters_nearest'].unique())
print(real_estate_data['cityCenters_nearest'].value_counts())
print(real_estate_data['cityCenters_nearest'].max())
print(real_estate_data['cityCenters_nearest'].min())

def cityCenters_to_group(row):
    income = row['cityCenters_nearest']
    if income <= 2000. :
        return 'on_center'
    elif income <= 10000.:
        return 'close_range'
    elif income <= 20000.:
        return 'far_range'
    return 'suburb_range'

real_estate_data['cityCenters_group'] = real_estate_data.apply(cityCenters_to_group, axis=1)
print(real_estate_data['cityCenters_group'].value_counts())

In [ ]:
print(real_estate_data['floors_total'].unique())

def floors_to_type(row):
    income = row['floors_total']
    if income <= 3 :
        return 'private_house'
    return 'apartment'

real_estate_data['flor_type'] = real_estate_data.apply(floors_to_type, axis=1)
print(real_estate_data['flor_type'].value_counts())

In [ ]:
print(real_estate_data['airports_nearest'].unique())
print(real_estate_data['airports_nearest'].max())
print(real_estate_data['airports_nearest'].min())
print(real_estate_data['airports_nearest'].value_counts())

def airport_to_group(row):
    income = row['airports_nearest']
    if income <= 15000. :
        return 'close_range'
    elif income <= 50000.:
        return 'middle_range'
    return 'far_range'

real_estate_data['airport_group'] = real_estate_data.apply(airport_to_group, axis=1)
print(real_estate_data['airport_group'].value_counts())

In [ ]:
print(real_estate_data['total_images'].unique())

def total_images_to_group(row):
    income = row['total_images']
    if income <= 2 :
        return 'few'
    elif income <= 10:
        return 'medium'
    return 'impressive'

real_estate_data['total_images_group'] = real_estate_data.apply(total_images_to_group, axis=1)
print(real_estate_data['total_images_group'].value_counts())

In [ ]:
print(real_estate_data['total_area'].unique())
print(real_estate_data['total_area'].max())
print(real_estate_data['total_area'].min())

def total_area_to_group(row):
    income = row['total_area']
    if income <= 50. :
        return 'small'
    elif income <= 100.:
        return 'medium'
    return 'huge'

real_estate_data['total_area_group'] = real_estate_data.apply(total_area_to_group, axis=1)
print(real_estate_data['total_area_group'].value_counts())

In [ ]:
print(real_estate_data['studio'].unique())

In [ ]:
print(real_estate_data['rooms'].unique())
real_estate_data.drop(real_estate_data[real_estate_data['rooms'] < 2].index , inplace=True)
print(real_estate_data['rooms'].unique())

def rooms_to_group(row):
    income = row['rooms']
    if income <= 3 :
        return 'small'
    elif income <= 5:
        return 'medium'
    return 'villa'

real_estate_data['rooms_group'] = real_estate_data.apply(rooms_to_group, axis=1)
print(real_estate_data['rooms_group'].value_counts())

In [ ]:
print(real_estate_data['ponds_nearest'].unique())
real_estate_data['ponds_nearest'] =  real_estate_data['ponds_nearest'].fillna(real_estate_data['ponds_nearest'].mean())
print(real_estate_data['ponds_nearest'].unique())
print(real_estate_data['ponds_nearest'].max())
print(real_estate_data['ponds_nearest'].min())

def ponds_nearest_to_group(row):
    income = row['ponds_nearest']
    if income <= 200 :
        return 'close_range'
    elif income <= 800:
        return 'medium_range'
    return 'far_range'

real_estate_data['ponds_nearest_group'] = real_estate_data.apply(ponds_nearest_to_group, axis=1)
print(real_estate_data['ponds_nearest_group'].value_counts())

In [ ]:
print(real_estate_data['ponds_around3000'].unique())
real_estate_data['ponds_around3000'] = real_estate_data['parks_around3000'].fillna(0.0)

In [ ]:
print(real_estate_data['parks_nearest'].unique())
real_estate_data['parks_nearest'].dropna(inplace=True)

def parks_nearest_to_group(row):
    income = row['parks_nearest']/1000
    if income <= 20 :
        return 'close_range'
    elif income <= 500:
        return 'medium_range'
    return 'far_range'

real_estate_data['parks_nearest_group'] = real_estate_data.apply(parks_nearest_to_group, axis=1)
print(real_estate_data['parks_nearest_group'].value_counts())

In [ ]:
print(real_estate_data['kitchen_area'].unique())
real_estate_data['kitchen_area'].dropna(inplace=True)
print(real_estate_data['kitchen_area'].max())
print(real_estate_data['kitchen_area'].min())

def kitchen_to_group(row):
    income = row['kitchen_area']
    if income <= 5. :
        return 'small'
    elif income <= 15.:
        return 'medium'
    return 'huge'

real_estate_data['kitchen_group'] = real_estate_data.apply(kitchen_to_group, axis=1)
print(real_estate_data['kitchen_group'].value_counts())

In [ ]:
print(real_estate_data['last_price'].unique())
print(real_estate_data['last_price'].max())
print(real_estate_data['last_price'].min())

In [ ]:
print(real_estate_data['is_apartment'].unique())
real_estate_data['is_apartment'].dropna(inplace=True)
print(real_estate_data['is_apartment'].unique())

In [ ]:
print(real_estate_data['locality_name'].unique())

In [ ]:
print(real_estate_data['living_area'].unique())
real_estate_data['living_area'].dropna(inplace=True)
print(real_estate_data['living_area'].max())
print(real_estate_data['living_area'].min())

def living_to_group(row):
    income = row['living_area']
    if income <= 18. :
        return 'small'
    elif income <= 50.:
        return 'medium'
    return 'huge'

real_estate_data['linving_group'] = real_estate_data.apply(living_to_group, axis=1)
print(real_estate_data['linving_group'].value_counts())

In [ ]:
print(real_estate_data['parks_around3000'].unique())
real_estate_data['parks_around3000'] = real_estate_data['parks_around3000'].fillna(0.0)
print(real_estate_data['parks_around3000'].unique())

In [ ]:
print(real_estate_data['open_plan'].unique())
print(real_estate_data['open_plan'].value_counts())

### Conclusion

open_plan: few information for True variables
parks_nearest: strange information
studio: only false, not relevant
Many columns had to many unique values, so I tried to categorize them.
Columns with null objects that could be fill with a rasonable data like 'mean' for ceiling higt, or 0 for no informations of parks or ponds around 3 km, were filled. But for not rasonable data, there rows where deleted.
Other data that was impossible, like ceiling hight, was verified to standar information like houses above 2 meters.

### Step 3. Make calculations and add them to the table

In [4]:
def price_per_square_meter(row):
    price = row['last_price']
    meter = row['total_area']
    return (price/meter)

real_estate_data['price_per_square_meter'] = real_estate_data.apply(price_per_square_meter, axis=1)
print(real_estate_data['price_per_square_meter'].value_counts())
print(real_estate_data['price_per_square_meter'].unique())
print(real_estate_data['price_per_square_meter'].max())
print(real_estate_data['price_per_square_meter'].min())

100000.000000    116
75000.000000      43
83333.333333      43
80000.000000      37
66666.666667      32
                ... 
87628.865979       1
98823.529412       1
106524.633822      1
120695.404101      1
132336.655592      1
Name: price_per_square_meter, Length: 9327, dtype: int64
[ 92785.71428571 408176.10062893 100000.         ... 129903.97805213
  52542.37288136 149511.40065147]
1907500.0
111.8348623853211
0.600000    148
0.666667    137
0.500000     84
0.625000     64
0.583333     51
           ... 
0.747273      1
0.602546      1
0.654639      1
0.619938      1
0.609459      1
Name: living_area_ratio, Length: 7103, dtype: int64
[0.6125            nan 0.32       ... 0.60697674 0.62376238 0.55281207]
0.9834469328140214
0.02158273381294964
0.166667    124
0.133333    111
0.142857    109
0.125000     86
0.136364     81
           ... 
0.114155      1
0.212479      1
0.184758      1
0.222054      1
0.139063      1
Name: kitchen_area_ratio, Length: 6355, dtype: int64
[0.14821429  

In [ ]:
def living_area_ratio(row):
    living_area = row['living_area']
    meter = row['total_area']
    return (living_area/meter)

real_estate_data['living_area_ratio'] = real_estate_data.apply(living_area_ratio, axis=1)
print(real_estate_data['living_area_ratio'].value_counts())
print(real_estate_data['living_area_ratio'].unique())
print(real_estate_data['living_area_ratio'].max())
print(real_estate_data['living_area_ratio'].min())

In [ ]:
def kitchen_area_ratio(row):
    kitchen_area = row['kitchen_area']
    meter = row['total_area']
    return (kitchen_area/meter)

real_estate_data['kitchen_area_ratio'] = real_estate_data.apply(kitchen_area_ratio, axis=1)
print(real_estate_data['kitchen_area_ratio'].value_counts())
print(real_estate_data['kitchen_area_ratio'].unique())
print(real_estate_data['kitchen_area_ratio'].max())
print(real_estate_data['kitchen_area_ratio'].min())

In [ ]:
def which_floor(row):
    floor = row['floor']
    floors_total = row['floors_total']
    if floor == 1 :
        return 'first'
    elif floor == floors_total:
        return 'last'
    return 'other'

real_estate_data['which_floor'] = real_estate_data.apply(which_floor, axis=1)
print(real_estate_data['which_floor'].value_counts())

In [ ]:
real_estate_data['weekday'] = real_estate_data['first_day_exposition'].dt.weekday
print(real_estate_data['weekday'].value_counts())
real_estate_data['month'] = pd.DatetimeIndex(real_estate_data['first_day_exposition']).month
print(real_estate_data['month'].value_counts())
real_estate_data['year'] = pd.DatetimeIndex(real_estate_data['first_day_exposition']).year
print(real_estate_data['year'].value_counts())

### Step 4. Conduct exploratory data analysis and follow the instructions below:

4.1- Carefully investigate the following parameters: square area, price, number of rooms, and ceiling height. Plot a histogram for each parameter.

In [ ]:
real_estate_data.hist('total_area')
real_estate_data.hist('last_price')
real_estate_data.hist('rooms')
real_estate_data.hist('ceiling_height')
real_estate_data.hist('first_day_exposition')
real_estate_data.hist('days_exposition')

4.2- Examine the time it's taken to sell the apartment and plot a histogram. Calculate the mean and median and explain the average time it usually takes to complete a sale. When can a sale be considered to have happened rather quickly or taken an extra long time?

In [ ]:
print(real_estate_data['days_exposition'].mean())
print(real_estate_data['days_exposition'].median())

4.3- Which factors have had the biggest influence on an apartment’s price? Examine whether the value depends on the total square area, number of rooms, floor (top or bottom), or the proximity to the downtown area. Also study the correlation to the publication date: day of the week, month, and year.

In [ ]:
pd.plotting.scatter_matrix(real_estate_data[['price_per_square_meter','rooms','which_floor','cityCenters_nearest']], figsize=(10,10))
real_estate_data[['year','month','weekday','price_per_square_meter','rooms','which_floor','cityCenters_nearest']].corr()

4.4- Select the 10 localities with the largest number of ads then calculate the average price per square meter in these localities. Determine which ones have the highest and lowest housing prices. You can find this data by name in the ’locality_name’ column.

In [ ]:
largest_places = real_estate_data['locality_name'].value_counts().nlargest(n=10).index.tolist()
data_of_largest = real_estate_data[real_estate_data['locality_name'].isin(largest_places)].reset_index(drop=True)
data_of_largest.groupby(['locality_name'])['price_per_square_meter'].agg(['mean'])

4.5- Thoroughly look at apartment offers: Each apartment has information about the distance to the city center. Select apartments in Saint Petersburg (‘locality_name’). Your task is to pinpoint which area is considered to be downtown. In order to do that, create a column with the distance to the city center in km and round to the nearest whole number. Next, calculate the average price for each kilometer and plot a graph to display how prices are affected by the distance to the city center. Find a place on the graph where it shifts significantly. That's the downtown border.

In [ ]:
sp_data = real_estate_data[real_estate_data['locality_name'] == 'Санкт-Петербург']
sp_data['km_to_cityCenter'] = round(sp_data['cityCenters_nearest']/1000)
# print(sp_data.head())

4.6- Select all the apartments in the downtown and examine correlations between the following parameters: total area, price, number of rooms, ceiling height. Also identify the factors that affect an apartment’s price: number of rooms, floor, distance to the downtown area, and ad publication date. Draw your conclusions. Are they different from the overall deductions about the entire city?

In [ ]:
plt.plot([0, 30], [1.8*10**7, 1*10**7], 'k-')
sp_data.groupby(['km_to_cityCenter'])['last_price'].agg('mean').plot(figsize=(10,5), xticks=np.arange(0,40,2))
pd.plotting.scatter_matrix(real_estate_data[['last_price','cityCenters_nearest','total_area','rooms','ceiling_height']], figsize=(10,10))
real_estate_data[['year','month','weekday','last_price','cityCenters_nearest','total_area','rooms','ceiling_height']].corr()

### Conclusion

Most of the house are normal, same ceiling height, same are, price and number of rooms. This is probably since it is the normal population. It takes almost half a year in average to sell the house. The median and the histogram teach us that most of the houses take only 3 month to sell, but some few houses have stron influence to the average since they are waiting allot of time to be selled. We can see that some few months is regular, while more than a year is quiete irregular and something is wrong with the house or it price is too high for what they offer. The outlying values where removed already on task 2. The bigger the house is, the higher is the price. But, since most of the smaller houses are closer to the city center, there price is also pretty high. There is not a correlation to the publication date, they are all under 0.1. The locality the highest housing prices is: 'Санкт-Петербург' (Saint Petersburg) with a mean of- 111512.518781; and the lowest housing prices is: Всеволожск' (Vsevolozhsk) with a mean of- 65336.134341.
The closer to the city center, the higher is the price. Downtown finishes 9 km from the most centric place of the city and that is the border of the downtown. The number of rooms next to the downtown was very small, meining that small families or people without children live near the downtown.
Yes we can see that in the last years, smaller houses are being selled, and they are closer to the city center. Also, there prices are getting down and being sell cheaper. The week and the month does not affect.
It seems that the nearest you are from downtown, the higher is the price, but the still the correlation is weak.

### Step 5. Overall conclusion

The data had allot of information, which some of them helped but some of them were irelevant.
In the pre-process I clean the data, categorize most of it since allot of the data had to many uniques information.
The dat had missing values for most of the cities, and the majority of the apartments were from St. Petersburg.

We learn that the median was under the mean, meaning that most of the apartments are been sell by less than the mean average. Most of the apartments are for the city center, were the number of rooms decreases.

By ploting the data of Saint Ptersburg, we could learn were ther border of the city-center goes threw. Also we noticed that Saint Ptersburg is the most expensive city for the price per square meter. 

Moreover, we learned that the prices are gettin down from last years, the houses that are been sailed are smaller than
